name: Build LaTeX and Release PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install TeX and fonts
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra texlive-science texlive-xetex texlive-fonts-recommended texlive-lang-chinese fonts-wqy-microhei
        sudo mkdir -p /usr/share/fonts/truetype/custom
        sudo cp fonts/SimSun.ttf /usr/share/fonts/truetype/custom/
        sudo fc-cache -fv
      
    - name: Compile tex files to pdf
      run: |
        for file in en_ton en_tvm en_tblkch en_catchain en_fiftbase zh_ton zh_tvm zh_tblkch zh_catchain zh_fiftbase; do
          if git diff --name-only HEAD~1 | grep "$file.tex"; then
            xelatex "$file.tex"
            xelatex "$file.tex"
          fi
        done

    - name: Remove auxiliary LaTeX files
      run: |
        rm -f *.aux *.log *.out *.toc

    - name: Commit PDF files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add *.pdf
        git commit -m "Add generated PDFs" || echo "No changes to commit"
        git push
  
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: release-${{ github.sha }}
        release_name: Release ${{ github.sha }}
        draft: false
        prerelease: false

    - name: Upload en_ton.pdf to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./en_ton.pdf
        asset_name: en_ton.pdf
        asset_content_type: application/pdf

    - name: Upload en_tvm.pdf to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./en_tvm.pdf
        asset_name: en_tvm.pdf
        asset_content_type: application/pdf

    - name: Upload en_tblkch.pdf to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./en_tblkch.pdf
        asset_name: en_tblkch.pdf
        asset_content_type: application/pdf

    - name: Upload en_catchain.pdf to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./en_catchain.pdf
        asset_name: en_catchain.pdf
        asset_content_type: application/pdf

    - name: Upload en_fiftbase.pdf to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./en_fiftbase.pdf
        asset_name: en_fiftbase.pdf
        asset_content_type: application/pdf

    - name: Upload zh_ton.pdf to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./zh_ton.pdf
        asset_name: zh_ton.pdf
        asset_content_type: application/pdf

    - name: Upload zh_tvm.pdf to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./zh_tvm.pdf
        asset_name: zh_tvm.pdf
        asset_content_type: application/pdf

    - name: Upload zh_tblkch.pdf to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./zh_tblkch.pdf
        asset_name: zh_tblkch.pdf
        asset_content_type: application/pdf

    - name: Upload zh_catchain.pdf to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./zh_catchain.pdf
        asset_name: zh_catchain.pdf
        asset_content_type: application/pdf

    - name: Upload zh_fiftbase.pdf to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./zh_fiftbase.pdf
        asset_name: zh_fiftbase.pdf
        asset_content_type: application/pdf
  