name: Build and Release PDFs

on:
  push:
    branches:
      - main  # or the name of your default branch

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup LaTeX
      uses: dante-ev/latex-action@2.0.0
      with:
        root_file: main.tex  # This is not used but required by the action

    - name: Compile all tex files
      run: |
        mkdir pdfs
        for texfile in $(find . -name "*.tex"); do
          # Get the name without the extension
          base_name=$(basename $texfile .tex)
          pdflatex -output-directory=pdfs -interaction=nonstopmode -halt-on-error $texfile
          mv pdfs/$base_name.pdf pdfs/${base_name}_$(date +%Y%m%d).pdf
        done

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: pdfs/*.pdf
        asset_name: ${{ steps.compile.outputs.name }}
        asset_content_type: application/pdf
